name: Linters

on:
  push:
    branches:
      - main

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - hello-backend
          - hello-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run linters
        uses: ./${{ matrix.directory }}/.github/workflows/linters.yml
